<?xml version="1.0"?>
<package format="3">
  <name>rl_enhanced_gz_scene_timelapse</name>
  <version>0.1.0</version>
  <description>Gazebo scene package for the fixed RL_enhanced 3D doorway environment.</description>

  <maintainer email="eugene@example.com">eugene</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>gz_sim_vendor</build_depend>
  <build_depend>gz_plugin_vendor</build_depend>
  <build_depend>gz_math_vendor</build_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>gz_sim_vendor</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
